### ISSUE TITLE
Installation receipt format

### ISSUE THREAD

**Issue by njlr** [LoopPerfect/buckaroo#193]
## Header

Given that the file is a receipt, I'm not sure the header makes sense. 

```toml=
[receipt]
path = "././buckaroo/github/LoopPerfect/r3"
lastUpdated = "07/12/2018 11:34:35"
type = "github"
...
```

should be: 

```
path = "././buckaroo/github/LoopPerfect/r3"
lastUpdated = "07/12/2018 11:34:35"
type = "github"
...
```

## Fragmented identifier

In other areas of the code we switch on presence of tags to determine discriminated union type. 

So this: 

```toml=
type = "github"
owner = "LoopPerfect"
project = "r3"
```

Should be: 

```toml=
package = "github.com/LoopPerfect/r3"
```

And for HTTP: 

```toml=
type = "http"
owner = "abc"
project = "def"
url = "https://abc.com/def.zip"
```

Should be just: 

```toml=
url = "https://abc.com/def.zip"
```

Since the package identifier is not part of the location. 

## Path

What is this for? 

```toml=
path = "././buckaroo/github/LoopPerfect/r3"
```

## Last Updated

Currently:

```toml=
lastUpdated = "07/12/2018 11:34:35"
```

Should be: 

```toml=
last_updated = 2018-12-07T11:34:35
```

(See https://github.com/toml-lang/toml#local-date-time)

To follow Toml conventions.
