### ISSUE TITLE
Package messages / caveats

### ISSUE THREAD

**Issue by njlr** [LoopPerfect/buckaroo#239]
After a package is installed we should show any messages that it contains. 

Messages would be defined in the package manifest like this: 

```toml=
targets = [ "//:hello" ]

message = "What a cool package"
```
