### ISSUE TITLE
Dependency groups

### ISSUE THREAD

**Issue by njlr** [LoopPerfect/buckaroo#244]
The goal of this feature is to make it easier for users to extract dependencies for a particular usage or platform. 

Inside the manifest, we should allow the user to tag dependencies as belonging to particular groups. 

It might look like this: 

```toml=
[[dependency]]
package = "github.com/abc/def"
version = "*"
groups = [ "dev" ]

[[dependency]]
package = "github.com/abc/ijk"
version = "*"
groups = [ "macos" ]

[[dependency]]
package = "github.com/abc/lmno"
version = "*"
groups = [ "dev", "linux" ]
```

By default, a dependency would not belong to any groups. 

We would then provide a macro in `buckaroo_macros.bzl` that allows the user to extract all dependencies for a given group: 

```python=
load('//:buckaroo_macros.bzl', 'buckaroo_deps_from_group')

cxx_binary(
  name = 'app', 
  srcs = [
    'main.cpp', 
  ],
  platform_deps = [
    ('macos.*', buckaroo_deps_from_group('macos')),
  ], 
)
```

Open questions: 

 * What if the same package is in more than one dependency? Merge the groups?
 * What is a valid group? Alphanumeric?

This is how we should support development and platform dependencies.

**Comment by njlr** [comment]
Once we have tags on dependencies, the behaviour of `buckaroo_deps()` should change to return all deps that do not have any tags. 

We would introduce a new function for returning all deps for any tag `buckaroo_all_deps()` (name TBD)

**Comment by iwatakeshi** [comment]
Hi. This is just a thought, but I think it would be better to introduce a boolean to determine whether the dependency is for development. Also, instead of `groups`, you could introduce an array for the operating systems such as `os`. The result would look like this:

```toml
[[dependency]]
package = "github.com/abc/def"
version = "*"
dev = true 

[[dependency]]
package = "github.com/abc/ijk"
version = "*"
os = [ "macos" ]

[[dependency]]
package = "github.com/abc/lmno"
version = "*"
os = [ "linux" ]
```

**Comment by njlr** [comment]
Hi @iwatakeshi, thanks for the response! 

Our initial idea was exactly as you describe, with `os` and `dev` as built-in concepts. We came up with two issues with this approach. 

**1. What do the macros look like when the user extracts the dependency?**

With the "groups" approach, it looks like this: 

```python
macos_deps = buckaroo_deps_group([ 'macos' ])
macos_dev_deps = buckaroo_deps_group([ 'macos', 'dev' ])
```

But with the "os + dev" approach it (might) look like this: 

```python
macos_deps = buckaroo_deps_os('macos')
macos_dev_deps = buckaroo_deps_os_dev('macos') # Feels wrong!
```

I think the first way looks nicer. _What do you think?_

**2. How do we support other kinds of group?**

There might be more types of dependency, not just platform-specific or development-specific. 

With the "groups" approach, the user can just define a new group: 

```toml
[[dependency]]
package = "github.com/abc/lmno"
version = "*"
groups = [ "custom" ]
```

and use it like this: 

```python
custom_deps = buckaroo_deps_group([ 'custom' ])
```

I'm not sure how this could work with the "os + dev" approach. _Any ideas?_

**None of this is implemented yet, so we would appreciate your thoughts!**
