### ISSUE TITLE
Add --location option to add for ad-hoc dependencies

### ISSUE THREAD

**Issue by njlr** [LoopPerfect/buckaroo#328]
Currently the user must edit the TOML manually. 

This is _OK_, but we should also support this in the CLI. 

For example, this command:

```bash
buckaroo add owner/project@branch=master --location git@url/to/git/repo.git
```

Would generate this TOML: 

```toml
[[location]]
name = "owner/project"
git = "git@url/to/git/repo.git"

[[dependency]]
package = "owner/project"
version = "branch=master"
```

The exact syntax is still up for grabs.
