### ISSUE TITLE
Passing parameters to dependency

### ISSUE THREAD

**Issue by Tarik02** [LoopPerfect/buckaroo#344]
## Description
Sometimes it's needed to pass some parameters to a dependency. Let's look at an example. Let's consider we need to use [glad](https://github.com/Dav1dde/glad/) in our project. It generates OpenGL headers using python script. The script uses a [few parameters](https://github.com/Dav1dde/glad/#usage), so there is very much variants of package.

## Possible Fix
Use something like parameters (or features like in Rust's cargo). For example:
```toml
[[dependency]]
package = "buckaroo-pm/glad"
version = "branch=master"
features = {
    profile = "core",
    api = { gl = "3.2", gles = "" },
    extensions = [
        "GL_EXT_framebuffer_multisample",
        "GL_EXT_texture_filter_anisotropic"
    ]
}
```

## Context
I need to use GLAD as a buckaroo dependency.

## Your Environment
* Version used: Buckaroo 2.2.0
* Operating System and Architecture: Windows 10 x64

**Comment by njlr** [comment]
Parameters can be passed to Buckaroo packages via the command-line at build-time ([demo](https://github.com/njlr/buck-config-demo)). These can then be read by the `BUCK` files of the package in order to configure it. 

However, these flags are not part of the resolution process, so it is up to the user to determine the correct set of parameters. This can always _be made to work_, but it can prevent things from working out-of-the-box. 

I think this proposal would be a good improvement. 

An open question is how this should work in practice. Can a package require flags for its dependencies be enabled? Can a package mark flag-sets as conflicting? Should a package declare what are valid settings? What is the syntax? How does this interact with the resolver?

It would be good to discuss this before diving into an implementation.

**Comment by njlr** [comment]
Overview of Rust approach: https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section

**Comment by Tarik02** [comment]
So, there can be problem with this dependency tree:
- package1
  * package2
- package2

If we have parameters, this can became a real problem. This can be solved with something like [peer dependencies in NodeJS](https://nodejs.org/es/blog/npm/peer-dependencies/).

So, in this case, `package1` will have a peer dependency `package2` and root project will have a dependency `package2` which will be used by `package1`. Well, then `package1` will force root project to have a dependency `package2`. This approach needs some way to declare and merge features of `package2` from root project and `package1`. In particular, merging strategy can be defined in `package2` (for example `set`, `array`, etc.).

I think that features should be an object (but for simplicity without objects inside). So, there should be unit types (string, int). Then, the object will have only values of units and arrays (only of units).

About rust's dependencies based on features, we can use this syntax:
```toml
[[dependency]]
name = ...
condition = "feature1"
```

**Comment by Tarik02** [comment]
Conflicting feature sets can be checked by `BUCK` config, it seems that it is easier to implement them there than in buckaroo.

**Comment by njlr** [comment]
> If we have parameters, this can became a real problem. This can be solved with something like peer dependencies in NodeJS.

In Buckaroo, packages are "peer" (we call them "public") dependencies by _default_. To have a "private" dependency (like in NPM by default), whose version does not need to be shared with others, you must add `private = true`. 

> So, in this case, package1 will have a peer dependency package2 and root project will have a dependency package2 which will be used by package1. Well, then package1 will force root project to have a dependency package2. This approach needs some way to declare and merge features of package2 from root project and package1. In particular, merging strategy can be defined in package2 (for example set, array, etc.).

Your example is supported by Buckaroo. The manifest for `package` should be something like:

```toml=
[[dependency]]
package = "package1"
version = "*"
private = true
```

> Conflicting feature sets can be checked by BUCK config, it seems that it is easier to implement them there than in buckaroo.

This is true. It might be nice if a combination of packages that can never work due to the configurations is never picked by the resolver... but this might be expecting too much! 

> I think that features should be an object (but for simplicity without objects inside). So, there should be unit types (string, int). Then, the object will have only values of units and arrays (only of units).

Interesting. How would integers work with the "condition" syntax?

**Comment by njlr** [comment]
_Forgot to add:_ 

Buck builds lazily, so if you fetch all of the optional dependencies but do not enable the feature then that package will not be built. It is slightly less efficient (since we are "over fetching") but this is not a significant cost compared to "over building".

**Comment by Tarik02** [comment]
So, we need some condition syntax, for example:
```toml
condition = "feature1" # for boolean features
condition = "feature >= 5" # for integers/floats/versions
condition = "feature == 'abc'" # for previous ones/strings
condition = "'something' in feature" # for sets/arrays
```

My subjective opinion is that this should be enough. Also, if feature used in condition does not exist, we can consider the whole condition to be false.

**Comment by Tarik02** [comment]
Also, then there should be some way to pass features to BUCK configurations and to use them in some convenient way.

**Comment by Tarik02** [comment]
Hmm, how are they peer by default? So I can access some functions of package2 from package1 if I a project depends on package1 and package2?

**Comment by Tarik02** [comment]
In theory, we can avoid "overfetching":
First download `BUCK` file of dependency and then execute it until some point (for example, we will force to check features before adding any libraries or binaries).

**Comment by njlr** [comment]
> My subjective opinion is that this should be enough. Also, if feature used in condition does not exist, we can consider the whole condition to be false.

I like this! It would map cleanly to the Skylark (Python) types in Buck. 

> Also, then there should be some way to pass features to BUCK configurations and to use them in some convenient way.

This is done using the `read_config` function in Buck: https://buckbuild.com/skylark/generated/read_config.html

> Hmm, how are they peer by default? So I can access some functions of package2 from package1 if I a project depends on package1 and package2?

They are "public" in the sense that everyone gets the same version, not in the sense of C++, Java, etc. You can only access the targets of a dependency if you explicitly depend upon it. 

> In theory, we can avoid "overfetching":
> First download BUCK file of dependency and then execute it until some point (for example, we will force to check features before adding any libraries or binaries).

I think it would be hard to make this work, and it might not be worth it. Remember that Buckaroo packages are source-code, so they are quite small. 

A simpler approach would be to move the configuration logic into Buckaroo and then the BUCK files access the values from a configuration file generated by Buckaroo. This maintains the one way data-flow we have now: 

    Manifests -> Buckaroo -> BUCK files + configurations -> Buck -> Clang, GCC etc.

**Comment by Tarik02** [comment]
I think it's better to leave only `BUCK` and download the whole package in any case (at least, it can be changed in future).

Also, since we have `buckaroo_macros`, we can add functions for features into there.

**Comment by Tarik02** [comment]
But also, that type system is not always convenient for configuration in the example:
```toml
    api = { gl = "3.2", gles = "" },
```
Maybe we should allow using flat object as a feature?

**Comment by Tarik02** [comment]
Due to TOML restrictions, the config will look like:
```toml
[[dependency]]
package = "github.com/Tarik02/glfw"
version = "branch=fix-windows"

  [[dependency.feature]]
  name = "profile"
  value = "core"

  [[dependency.feature]]
  name = "api"
  value = { gl = "3.2", gles = "" }

  [[dependency.feature]]
  name = "extensions"
  value = [
    "GL_EXT_framebuffer_multisample",
    "GL_EXT_texture_filter_anisotropic"
  ]
```
